# Introduction

Please note: this brochure is a work in progress, barely started at this stage.
The statistics chapter is largely ready, but others are at various stages.
However, there still is the presentation ([bihealth.github.io/howtotalk](https://bihealth.github.io/howtotalk))
which is actually where my idea started.

If you have any comments, suggestions or corrections, click in the top
right corner of this page on the $<$ icon to open the
[Hypothesis](https://hypothes.is/) annotation sidebar – it requires a free
login, but is otherwise really useful and definitely worth it.
Alternatively, file a github issue at the repository for this book – 
[github.com/bihealth/howtotalk-book](https://github.com/bihealth/howtotalk-book).

## Who this book is for

The book records the different bits and pieces of advice I keep hearing
from and telling to my collaborators, students and colleagues. They are
mostly based on my experience as a statistician and computational biologist
working in a biomedical research environment. A lot of what I have to say I
had to learn the hard way – by commiting the mistakes I am now warning you
against. I chose what things to include in this book by asking myself:
"What do I wish I had known when I started out?" and: "What do I wish my
collaborators knew when we started working together?"

## Who am I to tell you this stuff?

## Bioinformatics, statistics and computational biology

We often refer to the whole general category of humans involved in
biological data analysis using computers as "bioinformaticians". However,
strictly speaking, bioinformaticians in the proper sense of the word are
those who develop algorithms, databases and software packages. Then, there
are those who use these tools to actual data, and the more precise term for
these people is "computational biologists". Finally, there are those of us
who walk around and criticize experimental designs and they are called
statisticians.

The truth is most of us have at least set a foot in all three camps, but
experience and interest usually make us specialize in one of them. In
especially statistics appears to be separated from the other two, with many
bioinformaticians having only a very limited understanding of it, and many
statisticians having no experience with high throughput biological data and
other applications which are the bread and butter of bioinformaticians and
computational biologists[^power].

[^power]: A notable case in point are practical calculation of statistical
  power in high-dimensional settings, which require expertise in both, 
  statistics and high-throughput data analysis.

```{dot}
#| fig-width: 12
graph G {
  layout = "neato"
  fontname = "Helvetica,Arial,sans-serif"
  scale = 1.2

  node [
		style = filled
		color = "#000000"
		fontname = "Helvetica,Arial,sans-serif"
    fontsize = 10
    shape = "box"
	]

  statistics [ fillcolor="#F8B229", style=filled, label="Statistics", fontsize=18 ]
  bioinformatics [ fontcolor="white", fillcolor="#481567", style=filled, label="Bioinformatics", fontsize=18 ]
  cbio [ fontcolor="white", fillcolor="#33638d", style=filled, label="Computational\nbiology", fontsize=18 ]

  "Computers and science" [ fontcolor="white", fontsize=20, label = "Computers\nand\nScience" ]

  "Computers and science" -- bioinformatics
  "Computers and science" -- cbio
  "Computers and science" -- statistics


  subgraph Bioinformatics {
    node [ style=filled, fillcolor="#481567cc", fontcolor="white", fontsize=14 ]
    bioinformatics -- algorithms -- implementation
    bioinformatics -- formalizations
    bioinformatics -- standards
    bioinformatics -- databases -- maintenance
  }

  subgraph cbio {
      node [ fontcolor="white", fillcolor="#33638dcc", style=filled, fontsize=14 ]
      cbio -- "data\nscience" -- "data\nstewardship"
      cbio -- "functional\ngenomics"
      "functional\ngenomics" -- "gene set\nenrichment"
      cbio -- "using tools"
      cbio -- "sequence\nanalysis" -- "phylogenies"
  }

  subgraph Statistics {
      node [ fillcolor="#F8B22999cc", style=filled, fontsize=14 ]
      statistics -- "hypothesis\ntesting"
      "hypothesis\ntesting" -- "p-values"
      "hypothesis\ntesting" -- "effect sizes"
      statistics -- "power analysis"
      statistics -- "linear\nmodeling" -- "hierarchical\nmodeling"
      statistics -- "visualizations"
      statistics -- "Bayesian\nstatistics"
  }

}
```


## What bioinformaticians like
